apiVersion: apps/v1
kind: Deployment
metadata:
  name: pruning-my-pothos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pruning-my-pothos
  template:
    metadata:
      labels:
        app: pruning-my-pothos
    spec:
      containers:
        - name: web
          image: <+artifacts.primary.image>
          ports:
            - containerPort: 80
